### ISSUE TITLE
Generates incorrect OTP for Onelogin 2FA

### ISSUE THREAD

**Issue by toransahu** [rsc/2fa#26]
I successfully added my OneLogin 2FA. But 2fa OTP are not matching with OneLogin Protect App's OTP:

```
$ 2fa -add onelogin  
2fa key for oneline:JQVMHTFQ8ESF
```

**Comment by rsc** [comment]
That secret JQVMHTFQ8ESF - which I hope you have revoked - contains an 8, making it not a valid base32 value. The base32 alphabet is "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567" (case-insensitive), and usually TOTP keys are longer as well. Not sure what is going on, but that's not the right kind of input for 2fa.

**Comment by toransahu** [comment]
Thanks for the clarification @rsc , I'll dig into OneLogin's TOTP implementaion.
