### ISSUE TITLE
How to generate codes after moving disk to the new computer?

### ISSUE THREAD

**Issue by ghost** [rsc/2fa#32]
Hi, I've got new laptop and currently I'm using the hard disk from the previous computer via external adapter that is plugged in to the USB port. The 2fa binary is now under `/media/newlaptop/4a2e296c-ecbe-4d27-a4ba-9990774170b4/home/oldlaptop/go/bin`. It works but the command `./2fa -list` does not show any registered keynames. How can I make it work, i.e. generate the codes for keynames I had in my old laptop?

**Comment by dmitshur** [comment]
2fa documentation states:

> The keychain is stored unencrypted in the text file `$HOME/.2fa`.
